/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package backupServer0;

import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.ServerSocket;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.SwingUtilities;

/**
 *
 * @author sebas
 */
public class BSForm extends javax.swing.JFrame {

    private boolean servidorActivo = false;
    private ServerSocket servidor;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BSForm.class.getName());

    /**
     * Creates new form BSForm
     */
    public BSForm() {
        setTitle("Servidor de Respaldos (Controlador)");
        initComponents();
        mostrarIpLocal();
    }

    private void mostrarIpLocal() {
        try {
            String ipLocal = null;

            Enumeration<NetworkInterface> interfaces = NetworkInterface.getNetworkInterfaces();
            for (NetworkInterface iface : Collections.list(interfaces)) {
                // Ignorar interfaces deshabilitadas o de loopback
                if (!iface.isUp() || iface.isLoopback() || iface.isVirtual()) {
                    continue;
                }

                Enumeration<InetAddress> direcciones = iface.getInetAddresses();
                for (InetAddress direccion : Collections.list(direcciones)) {
                    // Solo direcciones IPv4 no loopback
                    if (!direccion.isLoopbackAddress() && direccion.getHostAddress().indexOf(":") == -1) {
                        ipLocal = direccion.getHostAddress();
                        break;
                    }
                }
                if (ipLocal != null) {
                    break;
                }
            }

            if (ipLocal != null) {
                lbl_ipLocal.setText("IP Local: " + ipLocal);
            } else {
                lbl_ipLocal.setText("No se encontró IP válida");
            }
        } catch (Exception e) {
            lbl_ipLocal.setText("Error al obtener la IP: " + e.getMessage());
        }
    }
    
    private void solicitarRespaldo() {
        String ipCliente = txt_ipCliente.getText().trim();
        String rutaSolicitada = txt_rutaSolicitada.getText().trim();
        String rutaDestino = txt_rutaDestino.getText().trim();

        try (Socket socket = new Socket(ipCliente, 4000);
             DataOutputStream out = new DataOutputStream(socket.getOutputStream());
             InputStream in = socket.getInputStream()) {

            agregarMensaje("Conectado con cliente: " + ipCliente);
            out.writeUTF("SOLICITAR_BACKUP|" + rutaSolicitada);
            out.flush();

            File dirDestino = new File(rutaDestino);
            if (!dirDestino.exists()) dirDestino.mkdirs();

            String nombreArchivo = "respaldo_" + ipCliente.replace(".", "_") + "_" +
                    new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ".zip";

            File archivoDestino = new File(dirDestino, nombreArchivo);

            try (FileOutputStream fos = new FileOutputStream(archivoDestino)) {
                byte[] buffer = new byte[4096];
                int bytesRead;
                while ((bytesRead = in.read(buffer)) != -1) {
                    fos.write(buffer, 0, bytesRead);
                }
            }

            agregarMensaje("Respaldo recibido y guardado en: " + archivoDestino.getAbsolutePath());
            lbl_estado.setText("Respaldo completado.");

        } catch (Exception e) {
            agregarMensaje("Error: " + e.getMessage());
            lbl_estado.setText("Error en respaldo.");
        }
    }

    private void agregarMensaje(String msg) {
        SwingUtilities.invokeLater(() -> txt_area.append(
                "[" + new SimpleDateFormat("HH:mm:ss").format(new Date()) + "] " + msg + "\n"
        ));
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_solicitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        lbl_ipLocal = new javax.swing.JLabel();
        txt_ipCliente = new javax.swing.JTextField();
        txt_rutaSolicitada = new javax.swing.JTextField();
        txt_rutaDestino = new javax.swing.JTextField();
        lbl_estado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_solicitar.setText("Solicitar Respaldo");
        btn_solicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_solicitarActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        lbl_ipLocal.setText("IP Local: ...");

        lbl_estado.setText("Servidor listo.");

        jLabel1.setText("IP Cliente:");

        jLabel2.setText("Ruta a respaldar:");

        jLabel3.setText("Ruta destino servidor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(90, 90, 90))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(44, 44, 44)))
                                .addComponent(txt_ipCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_estado)
                                .addGap(8, 8, 8)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_solicitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_ipLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_rutaSolicitada, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_rutaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 102, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ipCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_estado)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_rutaSolicitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_rutaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ipLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_solicitar))
                .addContainerGap())
        );

        btn_solicitar.getAccessibleContext().setAccessibleName("btn_activar");
        lbl_ipLocal.getAccessibleContext().setAccessibleName("lbl_IpLocal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_solicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_solicitarActionPerformed
        new Thread(this::solicitarRespaldo).start();
    }//GEN-LAST:event_btn_solicitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BSForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_solicitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_ipLocal;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_ipCliente;
    private javax.swing.JTextField txt_rutaDestino;
    private javax.swing.JTextField txt_rutaSolicitada;
    // End of variables declaration//GEN-END:variables
}
